const questions = [
  ////////////////////////////////////////////////////////////////
  ///////////// GEO ////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////
  {
    id: 1,
    ease: 1,
    questionType: "Géographie",
    questionText: "Quelle est la capitale du Royaume-uni ?",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg/langfr-225px-Flag_of_the_United_Kingdom_%283-5%29.svg.png",
    answerOptions: [
      { answerText: "Manchester", isCorrect: false },
      { answerText: "Londres", isCorrect: true },
      { answerText: "Liverpool", isCorrect: false },
      { answerText: "Dublin", isCorrect: false },
    ],
  },
  {
    id: 2,
    ease: 1,
    questionType: "Géographie",
    questionText: "Quelle est la capitale de l'Espagne ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/langfr-225px-Flag_of_Spain.svg.png",
    answerOptions: [
      { answerText: "Madrid", isCorrect: true },
      { answerText: "Lisbone", isCorrect: false },
      { answerText: "Bilbao", isCorrect: false },
      { answerText: "Barcelone", isCorrect: false },
    ],
  },
  {
    id: 3,
    ease: 1,
    questionType: "Géographie",
    questionText: "Sur quel continent peut-on gravir le Kilimanjaro ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Mt._Kilimanjaro_12.2006.JPG/1200px-Mt._Kilimanjaro_12.2006.JPG",
    answerOptions: [
      { answerText: "Afrique", isCorrect: true },
      { answerText: "Asie", isCorrect: false },
      { answerText: "Europe", isCorrect: false },
      { answerText: "Antarctique", isCorrect: false },
    ],
  },
  {
    id: 4,
    ease: 2,
    questionType: "Géographie",
    questionText: "Quelle est la capitale de l'Australie ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/langfr-225px-Flag_of_Australia_%28converted%29.svg.png",
    answerOptions: [
      { answerText: "Brisbane", isCorrect: false },
      { answerText: "Melbourne", isCorrect: false },
      { answerText: "Sydney", isCorrect: false },
      { answerText: "Camberra", isCorrect: true },
    ],
  },
  {
    id: 5,
    ease: 2,
    questionType: "Géographie",
    questionText: "Quel est le plus grand océan ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mizen_Head_2695.jpg/280px-Mizen_Head_2695.jpg",
    answerOptions: [
      { answerText: "Indien", isCorrect: false },
      { answerText: "Atlantique", isCorrect: false },
      { answerText: "Pacifique", isCorrect: true },
      { answerText: "Arctique", isCorrect: false },
    ],
  },
  {
    id: 6,
    ease: 2,
    questionType: "Géographie",
    questionText: "Où admirer le Machu Picchu ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1200px-Machu_Picchu%2C_Peru.jpg",
    answerOptions: [
      { answerText: "Au Pérou", isCorrect: true },
      { answerText: "Au Chilli", isCorrect: false },
      { answerText: "Au Mexique", isCorrect: false },
      { answerText: "En Argentine", isCorrect: false },
    ],
  },
  {
    id: 7,
    ease: 3,
    questionType: "Géographie",
    questionText: "Combien y-a t'il de contients ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Mercator-projection.jpg/1200px-Mercator-projection.jpg",
    answerOptions: [
      { answerText: "5", isCorrect: false },
      { answerText: "6", isCorrect: false },
      { answerText: "7", isCorrect: true },
      { answerText: "8", isCorrect: false },
    ],
  },
  {
    id: 8,
    ease: 3,
    questionType: "Géographie",
    questionText: "Quelle est l'altitude du mont Blanc ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/4/4b/Mont_Blanc_depuis_Valmorel_2.jpg",
    answerOptions: [
      { answerText: "4907m", isCorrect: false },
      { answerText: "4807m", isCorrect: true },
      { answerText: "4707m", isCorrect: false },
      { answerText: "4607m", isCorrect: false },
    ],
  },
  {
    id: 9,
    ease: 3,
    questionType: "Géographie",
    questionText: "Quel est le plus long fleuve du monde ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/d/d5/River_gambia_Niokolokoba_National_Park.gif",
    answerOptions: [
      { answerText: "Le Mississippi", isCorrect: false },
      { answerText: "Le Nil", isCorrect: false },
      { answerText: "L'Amazone", isCorrect: true },
      { answerText: "Le Gange", isCorrect: false },
    ],
  },
  {
    id: 10,
    ease: 4,
    questionType: "Géographie",
    questionText: "Quel est le chef lieu de l'indre et loire ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/France_relief_location_map.jpg/230px-France_relief_location_map.jpg",
    answerOptions: [
      { answerText: "Tours", isCorrect: true },
      { answerText: "Bourges", isCorrect: false },
      { answerText: "Angers", isCorrect: false },
      { answerText: "Le Mans", isCorrect: false },
    ],
  },
  {
    id: 11,
    ease: 4,
    questionType: "Géographie",
    questionText: "Dans quel pays visiter Ankara ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/3/3c/YDA-Center-03.jpg",
    answerOptions: [
      { answerText: "En Turquie", isCorrect: true },
      { answerText: "En Inde", isCorrect: false },
      { answerText: "En Birmanie", isCorrect: false },
      { answerText: "En Australie", isCorrect: false },
    ],
  },
  {
    id: 12,
    ease: 4,
    questionType: "Géographie",
    questionText: "Quelle est la plus grande presqu'île de France ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/France_relief_location_map.jpg/230px-France_relief_location_map.jpg",
    answerOptions: [
      { answerText: "Quiberon", isCorrect: false },
      { answerText: "Rhuys", isCorrect: false },
      { answerText: "Noirmoutier", isCorrect: false },
      { answerText: "Crozon", isCorrect: true },
    ],
  },

  ////////////////////////////////////////////////////////////////
  ///////////// TECH ////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////

  {
    id: 13,
    ease: 1,
    questionType: "Technologies",
    questionText: "Qui est le PDG de Tesla?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/TeslaMotors_HQ_PaloAlto.jpg/1200px-TeslaMotors_HQ_PaloAlto.jpg",
    answerOptions: [
      { answerText: "Jeff Bezos", isCorrect: false },
      { answerText: "Elon Musk", isCorrect: true },
      { answerText: "Bill Gates", isCorrect: false },
      { answerText: "Tony Stark", isCorrect: false },
    ],
  },
  {
    id: 14,
    ease: 1,
    questionType: "Technologies",
    questionText: `Quelle entreprise fut fondée par Bill Gates ?`,
    img :"https://upload.wikimedia.org/wikipedia/commons/a/af/Bill_Gates_-_Nov._8%2C_2019.jpg",
    answerOptions: [
      { answerText: "Apple", isCorrect: false },
      { answerText: "Intel", isCorrect: false },
      { answerText: "Amazon", isCorrect: false },
      { answerText: "Microsoft", isCorrect: true },
    ],
  },
  {
    id: 15,
    ease: 1,
    questionType: "Technologies",
    questionText: `Quelle entreprise à créé l'Iphone ?`,
    img : "https://d1fmx1rbmqrxrr.cloudfront.net/cnet/i/edit/2020/12/iphone-12-test-une.jpeg",
    answerOptions: [
      { answerText: "Apple", isCorrect: true },
      { answerText: "Intel", isCorrect: false },
      { answerText: "Amazon", isCorrect: false },
      { answerText: "Microsoft", isCorrect: false },
    ],
  },
  {
    id: 16,
    ease: 2,
    questionType: "Technologies",
    questionText: `Quelle branche de Virgin n'existe pas ?`,
    img : "https://upload.wikimedia.org/wikipedia/fr/thumb/5/5b/Virgin_group_logo.svg/1200px-Virgin_group_logo.svg.png",
    answerOptions: [
      { answerText: "Virgin Mobile", isCorrect: false },
      { answerText: "Virgin Galactic", isCorrect: false },
      { answerText: "Virgin Atlantic ", isCorrect: false },
      { answerText: "Virgin Aerospace", isCorrect: true },
    ],
  },
  {
    id: 17,
    ease: 2,
    questionType: "Technologies",
    questionText: `Quelle entreprise de l'industrie créative fut fondé en 1997 ?`,
    img : "http://www.blogangelio.ovh/wp-content/uploads/2017/01/tv-remote-control.jpg",
    answerOptions: [
      { answerText: "Disney", isCorrect: false },
      { answerText: "Netflix", isCorrect: false },
      { answerText: "Warner Bros", isCorrect: false },
      { answerText: "Amazon", isCorrect: true },
    ],
  },
  {
    id: 18,
    ease: 2,
    questionType: "Technologies",
    questionText: `Quelle est le secteur d'activité de Blue Origin ?`,
    img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG5BKLMTwW2SZ59yd4VOwgbSEnYKrvEW_HsQ&usqp=CAU",
    answerOptions: [
      { answerText: "Spatial", isCorrect: true },
      { answerText: "Deep diving", isCorrect: false },
      { answerText: "Génétique", isCorrect: false },
      { answerText: "Militaire", isCorrect: false },
    ],
  },
  {
    id: 19,
    ease: 3,
    questionType: "Technologies",
    questionText: `Au cours de quelles années se déroule la 2eme révolution industrielle ?`,
    img : "https://i.pinimg.com/originals/aa/c3/ab/aac3ab7083e987ccc66124e159477343.jpg",
    answerOptions: [
      { answerText: "1820-1830", isCorrect: false },
      { answerText: "1890-1910", isCorrect: true },
      { answerText: "1910-1920", isCorrect: false },
      { answerText: "1940-1950", isCorrect: false },
    ],
  },
  {
    id: 20,
    ease: 3,
    questionType: "Technologies",
    questionText: `Qui est Fugaku ?`,
    img : "https://us.123rf.com/450wm/kritchanut/kritchanut1410/kritchanut141000121/32814147-homme-ic%C3%B4ne-silhouette-avec-point-d-interrogation-signe-sur-le-visage-notion-suspect.jpg",
    answerOptions: [
      { answerText: "Une IA", isCorrect: false },
      { answerText: "Un Robot", isCorrect: false },
      { answerText: "Un super calculateur", isCorrect: true },
      { answerText: "Un héro", isCorrect: false },
    ],
  },
  {
    id: 21,
    ease: 3,
    questionType: "Technologies",
    questionText: `Quel entreprise à créé le robot humanoïde Atlas ?`,
    img : "https://cdn2.excelsior.com.mx/media/styles/image800x600/public/pictures/2021/08/18/2628812.jpg",
    answerOptions: [
      { answerText: "Boston Dynamics", isCorrect: true },
      { answerText: "La NASA", isCorrect: false },
      { answerText: "Tesla", isCorrect: false },
      { answerText: "AMP Robotics", isCorrect: false },
    ],
  },
  {
    id: 22,
    ease: 4,
    questionType: "Technologies",
    questionText: `Quel est le plus grand radio-téléscope du monde ?`,
    img : "https://upload.wikimedia.org/wikipedia/commons/2/28/70-%D0%BC_%D0%B0%D0%BD%D1%82%D0%B5%D0%BD%D0%BD%D0%B0_%D0%9F-2500_%28%D0%A0%D0%A2-70%29.jpg",
    answerOptions: [
      { answerText: "Fast", isCorrect: true },
      { answerText: "James Webb", isCorrect: false },
      { answerText: "Hubble", isCorrect: false },
      { answerText: "VLT", isCorrect: false },
    ],
  },
  {
    id: 23,
    ease: 4,
    questionType: "Technologies",
    questionText: `Quel type de signal est le plus courrant en électronique ?`,
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Hameg_HM203-6_front.jpg/1200px-Hameg_HM203-6_front.jpg",
    answerOptions: [
      { answerText: "Rond", isCorrect: false },
      { answerText: "Triangle", isCorrect: false },
      { answerText: "Carré", isCorrect: true },
      { answerText: "Sinusoïdal", isCorrect: false },
    ],
  },
  {
    id: 24,
    ease: 4,
    questionType: "Technologies",
    questionText: `Quel débit maximum peut atteindre le réseau 4G ?`,
    img : "https://www.jechange.fr/wp-content/uploads/2018/10/technologie_4g.jpg",
    answerOptions: [
      { answerText: "50Mbit/s", isCorrect: false },
      { answerText: "150Mbit/s", isCorrect: true },
      { answerText: "250Mbit/s", isCorrect: false },
      { answerText: "500Mbit/s", isCorrect: false },
    ],
  },

  ////////////////////////////////////////////////////////////////
  ///////////// LITTE ////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////
  {
    id: 25,
    ease: 1,
    questionType: "Littérature",
    questionText: "Combien de tomes y a t-il dans la saga Harry Potter ?",
    img : "https://cache.cosmopolitan.fr/data/photo/w1200_h630_c17/1ec/harry-potter-film-famille-large.jpg",
    answerOptions: [
      { answerText: "1", isCorrect: false },
      { answerText: "4", isCorrect: false },
      { answerText: "6", isCorrect: false },
      { answerText: "7", isCorrect: true },
    ],
  },
  {
    id: 26,
    ease: 1,
    questionType: "Littérature",
    questionText: "Comment s'appèle le signe typographique  & ?",
    img : "http://ekladata.com/TA-K1QA5k4wpmcnwDXOCblRFBc0.jpg",
    answerOptions: [
      { answerText: "Croisillon", isCorrect: false },
      { answerText: "Esperluette", isCorrect: true },
      { answerText: "Arobase", isCorrect: false },
      { answerText: "Tilde", isCorrect: false },
    ],
  },
  {
    id: 27,
    ease: 1,
    questionType: "Littérature",
    questionText: "Qui est l'auteur de l'Iliade et l'Odyssé ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Odysseus-siren_Parthenope%2C_the_mythological_founder_of_Naples.jpg/250px-Odysseus-siren_Parthenope%2C_the_mythological_founder_of_Naples.jpg",
    answerOptions: [
      { answerText: "Platon", isCorrect: false },
      { answerText: "Homer", isCorrect: true },
      { answerText: "Descartes", isCorrect: false },
      { answerText: "Virgile", isCorrect: false },
    ],
  },
  {
    id: 28,
    ease: 2,
    questionType: "Littérature",
    questionText: "Qui a écrit les Fleurs du Mal ?",
    img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFGI9HZOzFrL3CRKa-tkVEoQ7tyqg0uXbrPA&usqp=CAU",
    answerOptions: [
      { answerText: "Rimbaud", isCorrect: false },
      { answerText: "Molière", isCorrect: false },
      { answerText: "Baudelaire", isCorrect: true },
      { answerText: "Hugo", isCorrect: false },
    ],
  },
  {
    id: 29,
    ease: 2,
    questionType: "Littérature",
    questionText: "Comment nomme t-on les syllabes en poésie ?",
    img : "https://static.wixstatic.com/media/92c61a_20f4027d29a5405f8219f80c6d1b7cff~mv2.png/v1/fill/w_366,h_229,al_c,q_85,usm_1.20_1.00_0.01,enc_auto/poesie.png",
    answerOptions: [
      { answerText: "Les Vers", isCorrect: false },
      { answerText: "Les Rimes", isCorrect: false },
      { answerText: "Les Pieds ", isCorrect: true },
      { answerText: "Les Doigts", isCorrect: false },
    ],
  },
  {
    id: 30,
    ease: 2,
    questionType: "Littérature",
    questionText: "Au théâtre en quoi divise t-on les pièces ?",
    img : "http://www.theatreinparis.com/uploads/images/article/la-nouvelle-seine-petits-theatres-paris-header.jpg",
    answerOptions: [
      { answerText: "En Scènes", isCorrect: false },
      { answerText: "En Faits", isCorrect: false },
      { answerText: "En Gestes ", isCorrect: false },
      { answerText: "En Actes", isCorrect: true },
    ],
  },
  {
    id: 31,
    ease: 3,
    questionType: "Littérature",
    questionText: "Qui sont : mais où et donc or ni car ?",
    img : "https://m.media-amazon.com/images/I/516VDCJBGSL.jpg",
    answerOptions: [
      { answerText: "Des compléments d'objet indirect", isCorrect: false },
      { answerText: "Des conjonctions de coordination", isCorrect: true },
      { answerText: "Des conjonctions de subordination", isCorrect: false },
      { answerText: "Des interjections", isCorrect: false },
    ],
  },
  {
    id: 32,
    ease: 3,
    questionType: "Littérature",
    questionText: "Quel roman a écrit Isaac Asimov ?",
    img : "https://www.sciencesetavenir.fr/assets/img/2017/06/01/cover-r4x3w1200-592fc9e535f65-054-mpaa083348.jpg",
    answerOptions: [
      { answerText: "Les Thanatonautes", isCorrect: false },
      { answerText: "La Guerre des Mondes", isCorrect: false },
      { answerText: "I, Robot", isCorrect: true },
      { answerText: "La Nuit des temps", isCorrect: false },
    ],
  },
  {
    id: 33,
    ease: 3,
    questionType: "Littérature",
    questionText:
      "Par quel mouvement a été inventé le jeu du « Cadavre exquis » ?",
      img : "https://img-31.ccm2.net/3C_FAZw5VCkM4yjV0PRWIB_-MFI=/910x/smart/71e649fb0f614bae93ff464024b9427d/ccmcms-hugo/24382799.jpg",
    answerOptions: [
      { answerText: "Le Symbolisme", isCorrect: false },
      { answerText: "L'Existentialisme", isCorrect: false },
      { answerText: "L'Expressionisme", isCorrect: false },
      { answerText: "Le Surréalisme", isCorrect: true },
    ],
  },
  {
    id: 34,
    ease: 4,
    questionType: "Littérature",
    questionText: "Qui a écrit la première édition du Dictionnaire ?",
    img :"https://api.canalacademies.com/sites/default/files/styles/metatag/public/images/themes/langue-fran%C3%A7aise.jpg?h=3fa9d8f0&itok=1WPfsno5",
    answerOptions: [
      { answerText: "Jacques de Tourreil", isCorrect: true },
      { answerText: "Charles Louis Montesquieu", isCorrect: false },
      { answerText: "Denis Diderot", isCorrect: false },
      { answerText: "Jean Le Rond d'Alembert", isCorrect: false },
    ],
  },
  {
    id: 35,
    ease: 4,
    questionType: "Littérature",
    questionText:
      "Au théâtre, comment nomme t-on les indications de jeu à destination des acteurs ?",
      img : "http://www.theatreinparis.com/uploads/images/article/la-nouvelle-seine-petits-theatres-paris-header.jpg",
    answerOptions: [
      { answerText: "Soliloques", isCorrect: false },
      { answerText: "Stichomythies", isCorrect: false },
      { answerText: "Apartés", isCorrect: false },
      { answerText: "Didascalies", isCorrect: true },
    ],
  },
  {
    id: 36,
    ease: 4,
    questionType: "Littérature",
    questionText: "Qui est Prix Nobel de Littérature 2022 ?",
    img : "https://actualitte.com/uploads/images/prix-nobel-litterature-recompense-lettres-615ab7ca0b025466623257.jpg",
    answerOptions: [
      { answerText: "Tatiana de Rosnay", isCorrect: false },
      { answerText: "Amélie Nothomb", isCorrect: false },
      { answerText: "Annie Ernaux", isCorrect: true },
      { answerText: "Audrey Diwan", isCorrect: false },
    ],
  },

  ////////////////////////////////////////////////////////////////
  ///////////// MATH ////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////
  {
    id: 37,
    ease: 1,
    questionType: "Mathématiques",
    questionText: "Comment s'appele le résultat d'une multiplication ?",
    img : "https://www.fiducial-office-solutions.fr/INTERSHOP/static/WFS/FOS-FR-Site/-/FOS/fr_FR/L/115119/115119.jpg",
    answerOptions: [
      { answerText: "Le Dividende", isCorrect: false },
      { answerText: "La Javel", isCorrect: false },
      { answerText: "Le Dénominateur", isCorrect: false },
      { answerText: "Le Produit", isCorrect: true },
    ],
  },
  {
    id: 38,
    ease: 1,
    questionType: "Mathématiques",
    questionText: "Où a été inventé le zéro ?",
    img : "https://download.vikidia.org/vikidia/fr/images/e/ec/Z%C3%A9ro.svg.png",
    answerOptions: [
      { answerText: "En Inde", isCorrect: true },
      { answerText: "En Egypte", isCorrect: false },
      { answerText: "En Grèce", isCorrect: false },
      { answerText: "En Turquie", isCorrect: false },
    ],
  },
  {
    id: 39,
    ease: 1,
    questionType: "Mathématiques",
    questionText: "Calculer : 3*7+2*10+2/2",
    img : "https://www.fiducial-office-solutions.fr/INTERSHOP/static/WFS/FOS-FR-Site/-/FOS/fr_FR/L/115119/115119.jpg",
    answerOptions: [
      { answerText: "42", isCorrect: true },
      { answerText: "116", isCorrect: false },
      { answerText: "21,5", isCorrect: false },
      { answerText: "162", isCorrect: false },
    ],
  },
  {
    id: 40,
    ease: 2,
    questionType: "Mathématiques",
    questionText: "Comment se nomme un nombre en base 16",
    img : "https://www.fiducial-office-solutions.fr/INTERSHOP/static/WFS/FOS-FR-Site/-/FOS/fr_FR/L/115119/115119.jpg",
    answerOptions: [
      { answerText: "Hexadécimal", isCorrect: true },
      { answerText: "Binaire", isCorrect: false },
      { answerText: "Décimal", isCorrect: false },
      { answerText: "Duodécimal", isCorrect: false },
    ],
  },
  {
    id: 41,
    ease: 2,
    questionType: "Mathématiques",
    questionText:
      "Comment se nomme le théorème permettant de calculer l'hypoténuse",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Triangle-notations.png/640px-Triangle-notations.png",
    answerOptions: [
      { answerText: "Thalès", isCorrect: false },
      { answerText: "Descartes", isCorrect: false },
      { answerText: "Pythagore", isCorrect: true },
      { answerText: "Fourier", isCorrect: false },
    ],
  },
  {
    id: 42,
    ease: 2,
    questionType: "Mathématiques",
    questionText: "Comment nome t-on le nombre au dessus d'une fraction",
    img : "https://www.wikihow.com/images_en/thumb/b/b7/Solve-Fraction-Questions-in-Math-Step-7-Version-3.jpg/v4-460px-Solve-Fraction-Questions-in-Math-Step-7-Version-3.jpg.webp",
    answerOptions: [
      { answerText: "Le Quotien", isCorrect: false },
      { answerText: "Le Dénominateur", isCorrect: true },
      { answerText: "Le Numérateur", isCorrect: false },
      { answerText: "Le Dividende", isCorrect: false },
    ],
  },
  {
    id: 43,
    ease: 3,
    questionType: "Mathématiques",
    questionText: "Le Cosinus c'est",
    img : "https://lachroniquefacile.fr/wp-content/uploads/2016/11/CtJvPgNXEAA6uJB-1.jpg",
    answerOptions: [
      { answerText: "Opposé / Adjacent", isCorrect: false },
      { answerText: "Adjacent / Hypothénuse", isCorrect: true },
      { answerText: "Hypothénuse / Opposé", isCorrect: false },
      { answerText: "Adjacent / Opposé", isCorrect: false },
    ],
  },
  {
    id: 44,
    ease: 3,
    questionType: "Mathématiques",
    questionText: "Combient vaut l'exponentiel de 0 ?",
    img : "https://www.fiducial-office-solutions.fr/INTERSHOP/static/WFS/FOS-FR-Site/-/FOS/fr_FR/L/115119/115119.jpg",
    answerOptions: [
      { answerText: "0", isCorrect: false },
      { answerText: "NaN", isCorrect: false },
      { answerText: "+infini", isCorrect: false },
      { answerText: "1", isCorrect: true },
    ],
  },
  {
    id: 45,
    ease: 3,
    questionType: "Mathématiques",
    questionText: "Comment appèle t-on l'oppérateur conditionnel ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Question_mark_alternate.svg/800px-Question_mark_alternate.svg.png",
    answerOptions: [
      { answerText: "Jointure", isCorrect: false },
      { answerText: "Tau", isCorrect: false },
      { answerText: "Ternaire", isCorrect: false },
      { answerText: "Booléen", isCorrect: true },
    ],
  },
  {
    id: 46,
    ease: 4,
    questionType: "Mathématiques",
    questionText: "Combien vaut le nombre d'or ?",
    img : "https://www.podcastscience.fm/wp-content/uploads/2011/03/golden-rectangles.png",
    answerOptions: [
      { answerText: "1,618", isCorrect: false },
      { answerText: "1,629", isCorrect: false },
      { answerText: "1,647", isCorrect: false },
      { answerText: "1,676", isCorrect: true },
    ],
  },
  {
    id: 47,
    ease: 4,
    questionType: "Mathématiques",
    img : "https://www.fiducial-office-solutions.fr/INTERSHOP/static/WFS/FOS-FR-Site/-/FOS/fr_FR/L/115119/115119.jpg",
    questionText: "Calculer :  √((1+(√cos0))/2)² ?",
    answerOptions: [
      { answerText: "0", isCorrect: false },
      { answerText: "1", isCorrect: true },
      { answerText: "+infini", isCorrect: false },
      { answerText: "0.5", isCorrect: false },
    ],
  },
  {
    id: 48,
    ease: 4,
    questionType: "Mathématiques",
    questionText: "Quel est la 6eme décimale de Pi ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Pi-symbol.svg/800px-Pi-symbol.svg.png",
    answerOptions: [
      { answerText: "9", isCorrect: false },
      { answerText: "7", isCorrect: false },
      { answerText: "5", isCorrect: false },
      { answerText: "2", isCorrect: true },
    ],
  },

  ////////////////////////////////////////////////////////////////
  ///////////// SCIENCE ////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////
  {
    id: 49,
    ease: 1,
    questionType: "Sciences",
    questionText: "Comment appele t-on les constituants de la matière ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Tableau_periodique_Z_et_nom_fr.svg/771px-Tableau_periodique_Z_et_nom_fr.svg.png",
    answerOptions: [
      { answerText: "Cellules", isCorrect: false },
      { answerText: "Molécules", isCorrect: false },
      { answerText: "Atomes", isCorrect: true },
      { answerText: "Protéines", isCorrect: false },
    ],
  },
  {
    id: 50,
    ease: 1,
    questionType: "Sciences",
    questionText: "Comment nome t-on cette molécule : H2O ?",
    img : "https://media.kartable.fr/uploads/finalImages/final_5d2f33b8c36950.17309373.png",
    answerOptions: [
      { answerText: "De L'eau", isCorrect: true },
      { answerText: "Du Dihydrogène", isCorrect: false },
      { answerText: "Du Tritium", isCorrect: false },
      { answerText: "De L'oxygène", isCorrect: false },
    ],
  },
  {
    id: 51,
    ease: 1,
    questionType: "Sciences",
    questionText: "Quelle science s'interesse à la lumière ?",
    img : "https://parlonssciences.ca/sites/default/files/2020-02/abstract_light.jpg",
    answerOptions: [
      { answerText: "L'obstétrique", isCorrect: false },
      { answerText: "L'ophtalmologie", isCorrect: false },
      { answerText: "L'optique", isCorrect: true },
      { answerText: "La climatologie", isCorrect: false },
    ],
  },
  {
    id: 52,
    ease: 2,
    questionType: "Sciences",
    questionText: "Quelle est la vitesse approximative de la lumière?",
    img : "https://parlonssciences.ca/sites/default/files/2020-02/abstract_light.jpg",
    answerOptions: [
      { answerText: "300Km/s", isCorrect: true },
      { answerText: "200Km/s", isCorrect: false },
      { answerText: "400Km/s", isCorrect: false },
      { answerText: "500Km/s", isCorrect: false },
    ],
  },
  {
    id: 53,
    ease: 2,
    questionType: "Sciences",
    questionText: "Comment s'appèle l'étude des insectes ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Insect_collage.png/800px-Insect_collage.png",
    answerOptions: [
      { answerText: "Entomologie", isCorrect: true },
      { answerText: "Anthropologie", isCorrect: false },
      { answerText: "Anthologie", isCorrect: false },
      { answerText: "Ethologie", isCorrect: false },
    ],
  },
  {
    id: 54,
    ease: 2,
    questionType: "Sciences",
    questionText: "Comment se nomme l'étude du mouvement des planètes ?",
    img : "https://cdn.futura-sciences.com/buildsv6/images/largeoriginal/7/7/1/77199ef8fe_50034209_iau0603a-planete-02.jpg",
    answerOptions: [
      { answerText: "Astrologie", isCorrect: false },
      { answerText: "Astronomie", isCorrect: true },
      { answerText: "Astromancie", isCorrect: false },
      { answerText: "Astrognosie", isCorrect: false },
    ],
  },
  {
    id: 55,
    ease: 3,
    questionType: "Sciences",
    questionText:
      "Quel physicien donna son nom à un théorème de mécanique des fluides ?",
      img : "https://sciencequotidien.weebly.com/uploads/2/6/3/8/26384474/4368958.jpg?407",
    answerOptions: [
      { answerText: "Mayer", isCorrect: false },
      { answerText: "Joule", isCorrect: false },
      { answerText: "Bernouilli", isCorrect: true },
      { answerText: "Boltzmann", isCorrect: false },
    ],
  },
  {
    id: 56,
    ease: 3,
    questionType: "Sciences",
    questionText: "Combien de milliards d'étoiles composent la Voie Lactée ?",
    img : "https://static.nationalgeographic.fr/files/styles/image_3200/public/79574.adapt_.1900.1.jpg?w=1900&h=1268",
    answerOptions: [
      { answerText: "50 à 200", isCorrect: false },
      { answerText: "200 à 400", isCorrect: true },
      { answerText: "400 à 600", isCorrect: false },
      { answerText: "600 à 800", isCorrect: false },
    ],
  },
  {
    id: 57,
    ease: 3,
    questionType: "Sciences",
    questionText:
      "Par quelle réaction des réactifs s'échangent ils des électrons ?",
      img : "https://scitechdaily.com/images/Atom-Electrons.jpg",
    answerOptions: [
      { answerText: "Acido-basique", isCorrect: false },
      { answerText: "Combustion", isCorrect: false },
      { answerText: "Oxydoréduction", isCorrect: true },
      { answerText: "Métathèse", isCorrect: false },
    ],
  },
  {
    id: 58,
    ease: 4,
    questionType: "Sciences",
    questionText: "Qui est l'inventeur de la taxonomie ?",
    img : "https://www.rom.on.ca/sites/default/files/imce/taxonomy_phylogenetic_tree_of_life.png",
    answerOptions: [
      { answerText: "Darwin", isCorrect: false },
      { answerText: "Von Linné", isCorrect: true },
      { answerText: "Bloom", isCorrect: false },
      { answerText: "De Candolle", isCorrect: false },
    ],
  },
  {
    id: 59,
    ease: 4,
    questionType: "Sciences",
    questionText: "Combien y-a t'il d'électrons dans la couche M ?",
    img : "https://www.superprof.fr/ressources/wp-content/uploads/2017/07/atome-de-carbone-couche-electronique.jpg",
    answerOptions: [
      { answerText: "18", isCorrect: true },
      { answerText: "32", isCorrect: false },
      { answerText: "50", isCorrect: false },
      { answerText: "72", isCorrect: false },
    ],
  },
  {
    id: 60,
    ease: 4,
    questionType: "Sciences",
    questionText: "Quel français a reçu le Prix Nobel de physique 2022 ?",
    img: "https://www.slate.fr/sites/default/files/styles/1060x523/public/prix_nobel_2.jpg",
    answerOptions: [
      { answerText: "Étienne Klein", isCorrect: false },
      { answerText: "Alain Aspect", isCorrect: true },
      { answerText: "Aurélien Barrau", isCorrect: false },
      { answerText: "David Elbaz", isCorrect: false },
    ],
  },

  ///////////////////////////////////////////////////////////////
  ///////////// CULTURE G ///////////////////////////////////////
  ///////////////////////////////////////////////////////////////
  {
    id: 61,
    ease: 1,
    questionType: "Culture Générale",
    questionText: "Qui chante : Someone like you ?",
    img : "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzNzYzNn0?utm_source=dictionnaire&utm_medium=referral",
    answerOptions: [
      { answerText: "Abdel", isCorrect: false },
      { answerText: "Odile", isCorrect: false },
      { answerText: "Adèle", isCorrect: true },
      { answerText: "Snoop Dog", isCorrect: false },
    ],
  },
  { 
    id:62,
    ease: 1,
    questionType: "Culture Générale",
    questionText: "De quel groupe comique Alain Chabat est il le membre le plus connu ?",
    img : "https://kultt.fr/wp-content/uploads/2022/09/TF1-theLateShow-AlainChabat-uai-900x506.jpg",
    answerOptions: [
      { answerText: "Les Robins des Bois", isCorrect: false },
      { answerText: "Les Inconnus", isCorrect: false },
      { answerText: "Les Nuls", isCorrect: true },
      { answerText: "Mais qui donc est Alain Chabat ?", isCorrect: false },
    ],
  },
  {
    id:63,
    ease: 1,
    questionType: "Culture Générale",
    questionText: "Que perdez-vous si vous êtes aphone ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Question_mark_alternate.svg/800px-Question_mark_alternate.svg.png",
    answerOptions: [
      { answerText: "Votre téléphone", isCorrect: false },
      { answerText: "Vos animaux", isCorrect: false },
      { answerText: "Votre équilibre", isCorrect: false },
      { answerText: "Votre voix", isCorrect: true },
    ],
  },
  {
    id:64,
    ease: 2,
    questionType: "Culture Générale",
    questionText: "Combien y-a t'il de Dragon Ball ?",
    img : "https://cdn.shopify.com/s/files/1/0039/8668/6063/files/goku_465c91e7-392b-450b-9766-1126172e0a5e.png?v=1560804742",
    answerOptions: [
      { answerText: "5", isCorrect: false },
      { answerText: "7", isCorrect: true },
      { answerText: "9", isCorrect: false },
      { answerText: "11", isCorrect: false },
    ],
  },
  {
    id:65,
    ease: 2,
    questionType: "Culture Générale",
    questionText: "Quel animal était Laika, le premier être vivant à séjourner en orbite ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Apollo_11_Saturn_V_lifting_off_on_July_16%2C_1969.jpg/1200px-Apollo_11_Saturn_V_lifting_off_on_July_16%2C_1969.jpg",
    answerOptions: [
      { answerText: "Un Poisson", isCorrect: false },
      { answerText: "Un Chat", isCorrect: false },
      { answerText: "Un Singe", isCorrect: false },
      { answerText: "Un Chien", isCorrect: true },
    ],
  },
  {
    id:66,
    ease: 2,
    questionType: "Culture Générale",
    questionText: "Comment appelle-t-on la jupe portée par les danseuses de ballet ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Grandjete.jpg/1200px-Grandjete.jpg",
    answerOptions: [
      { answerText: "Un Jupon", isCorrect: false },
      { answerText: "Un Boléro", isCorrect: false },
      { answerText: "Une Ballerine", isCorrect: false },
      { answerText: "Un Tutu", isCorrect: true },
    ],
  },
  {
    id:67,
    ease: 3,
    questionType: "Culture Générale",
    questionText: "Quel est la bonne orthographe ?",
    img : "https://cdn.futura-sciences.com/buildsv6/images/largeoriginal/a/9/8/a980f899a5_50315_platypus.jpg",
    answerOptions: [
      { answerText: "Ornytorinque", isCorrect: false },
      { answerText: "Ornithorinque", isCorrect: false },
      { answerText: "Ornytorynque", isCorrect: false },
      { answerText: "Ornithorynque", isCorrect: true },
    ],
  },
  {
    id:68,
    ease: 3,
    questionType: "Culture Générale",
    questionText: "Que siginfie ADN ?",
    img : "https://file1.topsante.com/var/topsante/storage/images/1/3/1/9/1319211/adn.jpg?alias=exact540x405_l&size=x100&format=jpeg",
    answerOptions: [
      { answerText: "Adénosine-Désoxyribo-Nucléïque", isCorrect: false },
      { answerText: "Acide-Désoxyribo-Nucléïque", isCorrect: true },
      { answerText: "Adénosisne-Désoxyribo-Nucléaire", isCorrect: false },
      { answerText: "Acide-Désoxyribo-Nucléaire ", isCorrect: false },
    ],
  },
  {
    id:69,
    ease: 3,
    questionType: "Culture Générale",
    questionText: "Qui a écrit le premier évangile ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Jevan%C4%91elje_iz_Crkoleza%2C_XIII_vek.jpg/310px-Jevan%C4%91elje_iz_Crkoleza%2C_XIII_vek.jpg",
    answerOptions: [
      { answerText: "Mathieu", isCorrect: false },
      { answerText: "Luc", isCorrect: false },
      { answerText: "Marc", isCorrect: true },
      { answerText: "Jean", isCorrect: false },
    ],
  },
  {
    id:70,
    ease: 4,
    questionType: "Culture Générale",
    questionText: "Qui est le prophète selon la religion Rastafarï ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Ethiopia_%281897%E2%80%931974%29.svg/1200px-Flag_of_Ethiopia_%281897%E2%80%931974%29.svg.png",
    answerOptions: [
      { answerText: "Marcus Garvey", isCorrect: true },
      { answerText: "Malcolm X", isCorrect: false },
      { answerText: "Haïlé Sélassié Ier", isCorrect: false },
      { answerText: "Martin Luther King", isCorrect: false },
    ],
  },
  {
    id:71,
    ease: 4,
    questionType: "Culture Générale",
    questionText: "Combien de pages possède un passport grand voyageur ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/French_Passport_Cover.svg/1200px-French_Passport_Cover.svg.png",
    answerOptions: [
      { answerText: "44", isCorrect: false },
      { answerText: "48", isCorrect: true },
      { answerText: "52", isCorrect: false },
      { answerText: "56", isCorrect: false },
    ],
  },
  {
    id:72,
    ease: 4,
    questionType: "Culture Générale",
    questionText: "Qu'est ce qu'une litote ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Question_mark_alternate.svg/800px-Question_mark_alternate.svg.png",
    answerOptions: [
      { answerText: "Un poisson des abysses", isCorrect: false },
      { answerText: "Une fleur endémique", isCorrect: false },
      { answerText: "Une figure de style", isCorrect: true },
      { answerText: "Un outil de sculpture", isCorrect: false },
    ],
  },
  ////////////////////////////////////////////////////////////////
  ///////////// SPORT ////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////
  {
    id:73,
    ease: 1,
    questionType: "Sport",
    questionText: "Quelle est la longueur en mètres d’une piscine dite olympique ?",
    img : "https://www.maisonapart.com/images/auto/640-480-c/20110519_165825_casto-3.jpg",
    answerOptions: [
      { answerText: "25 ", isCorrect: false },
      { answerText: "50", isCorrect: true },
      { answerText: "100", isCorrect: false },
      { answerText: "200", isCorrect: false },
    ],
  },
  {
    id:74,
    ease: 1,
    questionType: "Sport",
    questionText: "Combien de mètres courent les sprinter ?",
    img : "https://fr.jbl.com/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw4029c47d/pdp/JBL_Endurance_Sprint_Lifestyle_f01.jpg",
    answerOptions: [
      { answerText: "25", isCorrect: false },
      { answerText: "50", isCorrect: false },
      { answerText: "100", isCorrect: true },
      { answerText: "200", isCorrect: false },
    ],
  },
  {
    id:75,
    ease: 1,
    questionType: "Sport",
    questionText: "Combien de joueurs composent une équipe de football ?",
    img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXO3as9Wkqdozv-_iVFJ6A1rWgZdr_gfwTrA&usqp=CAU",
    answerOptions: [
      { answerText: "8", isCorrect: false },
      { answerText: "9", isCorrect: false },
      { answerText: "10", isCorrect: false },
      { answerText: "11", isCorrect: true },
    ],
  },
  {
    id:76,
    ease: 2,
    questionType: "Sport",
    questionText:"Pendant le tour de France, quelle est la couleur du maillot du meilleure sprinter ?",
    img : "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f2/Tour_de_France_logo_2019.svg/1200px-Tour_de_France_logo_2019.svg.png",
    answerOptions: [
      { answerText: "Jaune", isCorrect: false },
      { answerText: "Blanc", isCorrect: false },
      { answerText: "Vert", isCorrect: true },
      { answerText: "À pois", isCorrect: false },
    ],
  },
  {
    id:77,
    ease: 2,
    questionType: "Sport",
    questionText:
      "Quel sportif est le plus médaillé de l'histoire des JO ?",
      img : "https://www.leparisien.fr/resizer/-juH-R4kBQ0_Bzhy2J2h6WeAlnY=/932x582/cloudfront-eu-central-1.images.arcpublishing.com/lpguideshopping/BDA27JCVDVHE5OMQ3MGXW76SNU.jpg",
    answerOptions: [
      { answerText: "Michael Phelps", isCorrect: true },
      { answerText: "Mark Spitz", isCorrect: false },
      { answerText: "Larissa Latynina", isCorrect: false },
      { answerText: "Paavo Nurmi", isCorrect: false },
    ],
  },
  {
    id:78,
    ease: 2,
    questionType: "Sport",
    questionText:"Quel joueur a le plus de victoires en simple à Roland Garros ?",
    img : "https://padelmagazine.fr/wp-content/uploads/2019/11/roland-garros-2020.jpg",
    answerOptions: [
      { answerText: "Nadal", isCorrect: true },
      { answerText: "Federer", isCorrect: false },
      { answerText: "Evert", isCorrect: false },
      { answerText: "Decugis", isCorrect: false },
    ],
  },
  {
    id:79,
    ease: 3,
    questionType: "Sport",
    questionText:"Combien de joueurs composent une équipe de water-polo ?",
    img : "https://sf1.sport365.fr/wp-content/uploads/se/2018/07/millot-water-polo-750x410.jpg",
    answerOptions: [
      { answerText: "6", isCorrect: false },
      { answerText: "7", isCorrect: true },
      { answerText: "8", isCorrect: false },
      { answerText: "9", isCorrect: false },
    ],
  },
  {
    id:80,
    ease: 3,
    questionType: "Sport",
    questionText:"Quelle écurie de F1 détient le plus grand nombre de records ?",
    img : "https://www.f1actu.com/wp-content/uploads/2022/10/310092892_5768388849858362_7397304520535297583_n.jpg",
    answerOptions: [
      { answerText: "Merecedes", isCorrect: false },
      { answerText: "McLarren", isCorrect: false },
      { answerText: "Red Bull Racing", isCorrect: false },
      { answerText: "Ferrari", isCorrect: true },
    ],
  },

  {
    id:81,
    ease: 3,
    questionType: "Sport",
    questionText:"En 2012 dans quelle ville ont eu lieu les Jeux Olympiques ?",
    img : "https://www.leparisien.fr/resizer/-juH-R4kBQ0_Bzhy2J2h6WeAlnY=/932x582/cloudfront-eu-central-1.images.arcpublishing.com/lpguideshopping/BDA27JCVDVHE5OMQ3MGXW76SNU.jpg",
    answerOptions: [
      { answerText: "Londres", isCorrect: true },
      { answerText: "Pékin", isCorrect: false },
      { answerText: "Sotchi", isCorrect: false },
      { answerText: "Rio de Janerio", isCorrect: false },
    ],
  },
  {
    id:82,
    ease: 4,
    questionType: "Sport",
    questionText:"Quel est le record du monde actuel du saut à la perche détenu par le Suédois Armand Duplantis ?",
    img : "https://cdn-s-www.bienpublic.com/images/74BCDA25-A42D-4BFE-9E9A-82C0EABB4DE5/NW_raw/photo-sipa-charlie-riedel-1658727546.jpg",
    answerOptions: [
      { answerText: "5m61", isCorrect: false },
      { answerText: "5m81", isCorrect: false },
      { answerText: "6m01", isCorrect: false },
      { answerText: "6m21", isCorrect: true },
    ],
  },
  {
    id:83,
    ease: 4,
    questionType: "Sport",
    questionText:"Quel est la longueur en mètres d'un terrain de Football Américain ?",
    img : "https://resize-europe1.lanmedia.fr/r/622,311,forcex,center-middle/img/var/europe1/storage/images/europe1/sport/pourquoi-on-aime-le-football-americain-354682/7431142-1-fre-FR/Pourquoi-on-aime-le-football-americain.jpg",
    answerOptions: [
      { answerText: "100", isCorrect: false },
      { answerText: "110", isCorrect: true },
      { answerText: "120", isCorrect: false },
      { answerText: "130", isCorrect: false },
    ],
  },    
  {
    id:84,
    ease: 4,
    questionType: "Sport",
    questionText:"Au judo parmis ces arbitrages lequel vaut 5 points ?",
    img : "https://cloudfront-eu-central-1.images.arcpublishing.com/leparisien/7UFYNUB7VVBCDBS7FSY4K6K3PI.jpg",
    answerOptions: [
      { answerText: "Ippon", isCorrect: false },
      { answerText: "Yuko", isCorrect: true },
      { answerText: "Waza ari", isCorrect: false },
      { answerText: "Koka", isCorrect: false },
    ],
  },

////////////////////////////////////////////////////////////////
///////////// histoire /////////////////////////////////////////
////////////////////////////////////////////////////////////////
{
    id:85,
    ease: 1,
    questionType: "Histoire",
    questionText:"En quelle année se déroule la bataille de Marignan ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/0/09/Marignan.jpg",
    answerOptions: [
      { answerText: "1515", isCorrect: true },
      { answerText: "1616", isCorrect: false },
      { answerText: "1717", isCorrect: false },
      { answerText: "1818", isCorrect: false },
    ],
  },
  {
    id:86,
    ease: 1,
    questionType: "Histoire",
    questionText:"Quel est le premier roi de France ?",
    img : "https://www.seevisit.fr/uploads/seevisit-francs-presentation.jpg",
    answerOptions: [
      { answerText: "Charlemagne", isCorrect: false },
      { answerText: "Clovis", isCorrect: true },
      { answerText: "François 1er", isCorrect: false },
      { answerText: "Mérové", isCorrect: false },
    ],
  },
  {
    id:87,
    ease: 1,
    questionType: "Histoire",
    questionText:"En quelle année se termine la première guerre mondiale ?",
    img : "https://cdn.britannica.com/44/65944-050-F18FEEA4/soldier-British-trench-Western-Front-World-War.jpg",
    answerOptions: [
      { answerText: "1914", isCorrect: false },
      { answerText: "1918", isCorrect: true },
      { answerText: "1939", isCorrect: false },
      { answerText: "1945", isCorrect: false },
    ],
  },
  {
    id:88,
    ease: 2,
    questionType: "Histoire",
    questionText:"Qui a rendu l'école publique gratuite ?",
    img: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Klassenzimmer1930.jpg",
    answerOptions: [
      { answerText: "Charlemagne", isCorrect: false },
      { answerText: "Napoléon", isCorrect: false },
      { answerText: "Jules Ferry", isCorrect: true },
      { answerText: "Jean Jaurès", isCorrect: false },
    ],
  },
  {
    id:89,
    ease: 2,
    questionType: "Histoire",
    questionText:"Quelle ville abritait les jardins suspendus ?",
    img : "https://static.actu.fr/uploads/2019/03/ob_a67262_jardins-babylone-e1553869870647-960x640.jpg",
    answerOptions: [
      { answerText: "Athènes", isCorrect: false },
      { answerText: "Rome", isCorrect: false },
      { answerText: "Ur", isCorrect: false },
      { answerText: "Babylone", isCorrect: true },
    ],
  },
  {
    id:90,
    ease: 2,
    questionType: "Histoire",
    questionText:"Quel roi était surnommé le Roi Soleil ?",
    img: "https://www.lafabriqueduprof.fr/wp-content/uploads/2019/07/adobestock_159496279.jpg",
    answerOptions: [
      { answerText: "Louis XIII ", isCorrect: false },
      { answerText: "Louis XIV", isCorrect: true },
      { answerText: "Louis XV", isCorrect: false },
      { answerText: "Louis XVI", isCorrect: false },
    ],
  },
  {
    id:91,
    ease: 3,
    questionType: "Histoire",
    questionText:"En quelle année coula le Titanic ?",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/RMS_Titanic_3.jpg/800px-RMS_Titanic_3.jpg",
    answerOptions: [
      { answerText: "1912", isCorrect: true },
      { answerText: "1911", isCorrect: false },
      { answerText: "1910", isCorrect: false },
      { answerText: "1909", isCorrect: false },
    ],
  },
  {
    id:92,
    ease: 3,
    questionType: "Histoire",
    questionText:"Qui fut une des pionnières du féminisme ?",
    img : "https://i0.wp.com/lanouvellechronique.com/wp-content/uploads/2021/03/faust-3217339_1920-edited.png?resize=327%2C429&ssl=1",
    answerOptions: [
      { answerText: "Edith Cresson", isCorrect: false },
      { answerText: "Olympe de Gouges", isCorrect: true },
      { answerText: "Julie-Victoire Daubié", isCorrect: false },
      { answerText: "Maria Deraismes", isCorrect: false },
    ],
  },
  {
    id:93,
    ease: 3,
    questionType: "Histoire",
    questionText:"Dans quel pays Che Guevara est il né ?",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/CheHigh.jpg/280px-CheHigh.jpg",
    answerOptions: [
      { answerText: "Bolivie", isCorrect: false },
      { answerText: "Cuba", isCorrect: false },
      { answerText: "Argentine", isCorrect: true },
      { answerText: "Chilli", isCorrect: false },
    ],
  },
  {
    id:94,
    ease: 4,
    questionType: "Histoire",
    questionText:"Quel fût le plus grand Empire ?",
    img : "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Africa_from_low_orbiting_satellite_Suomi_NPP.jpg/1200px-Africa_from_low_orbiting_satellite_Suomi_NPP.jpg",
    answerOptions: [
      { answerText: "L'Empire Mongol", isCorrect: false },
      { answerText: "L'Empire Romain", isCorrect: false },
      { answerText: "L'Empire Britanique", isCorrect: true },
      { answerText: "L'Empire Russe", isCorrect: false },
    ],
  },
  {
    id:95,
    ease: 4,
    questionType: "Histoire",
    questionText:"À quelle période pouvait on fuire devant un Tyranosaure ?",
    img : "https://dailygeekshow.com/wp-content/uploads/2020/05/une-t-rex.jpeg",
    answerOptions: [
      
      { answerText: "Crétacé", isCorrect: true },
      { answerText: "Jurassique", isCorrect: false },
      { answerText: "Trias", isCorrect: false},
      { answerText: "Carbonnifère", isCorrect: false },
    ],
  },
  {
    id:96,
    ease: 4,
    questionType: "Histoire",
    questionText:"En quelle année meurt Napoléon II ?",
    img: "https://www.larousse.fr/encyclopedie/data/images/1005124-Napol%C3%A9on_II.jpg",
    answerOptions: [
      { answerText: "1810", isCorrect: false },
      { answerText: "1818", isCorrect: false },
      { answerText: "1826", isCorrect: false },
      { answerText: "1832", isCorrect: true },
    ],
  },
];


export default questions;
